const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.Platform,
		C3.Behaviors.solid,
		C3.Plugins.Touch,
		C3.Plugins.Text,
		C3.Behaviors.Bullet,
		C3.Plugins.Touch.Cnds.OnTapGestureObject,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.System.Exps.random,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.Touch.Cnds.IsTouchingObject,
		C3.Behaviors.Platform.Acts.SimulateControl
	];
};
self.C3_JsPropNameTable = [
	{BG: 0},
	{Plataforma: 0},
	{LixoVerde: 0},
	{LixoVermelho: 0},
	{LixoAzul: 0},
	{LixoAmarelo: 0},
	{Sólido: 0},
	{Chao: 0},
	{Direita: 0},
	{Esquerdo: 0},
	{Toque: 0},
	{unnamed: 0},
	{Sprite: 0},
	{Sprite2: 0},
	{Sprite3: 0},
	{Sprite4: 0},
	{Sprite5: 0},
	{Sprite6: 0},
	{Sprite7: 0},
	{Sprite8: 0},
	{Sprite9: 0},
	{Sprite10: 0},
	{Sprite11: 0},
	{Sprite12: 0},
	{Texto2: 0},
	{latinhaPx: 0},
	{Projétil: 0},
	{latinha2Px: 0},
	{garrafaPx: 0},
	{papelPx: 0},
	{vidropx: 0},
	{Ponto: 0}
];

self.InstanceType = {
	BG: class extends self.ISpriteInstance {},
	LixoVerde: class extends self.ISpriteInstance {},
	LixoVermelho: class extends self.ISpriteInstance {},
	LixoAzul: class extends self.ISpriteInstance {},
	LixoAmarelo: class extends self.ISpriteInstance {},
	Chao: class extends self.ISpriteInstance {},
	Direita: class extends self.ISpriteInstance {},
	Esquerdo: class extends self.ISpriteInstance {},
	Toque: class extends self.IInstance {},
	unnamed: class extends self.ISpriteInstance {},
	Sprite: class extends self.ISpriteInstance {},
	Sprite2: class extends self.ISpriteInstance {},
	Sprite3: class extends self.ISpriteInstance {},
	Sprite4: class extends self.ISpriteInstance {},
	Sprite5: class extends self.ISpriteInstance {},
	Sprite6: class extends self.ISpriteInstance {},
	Sprite7: class extends self.ISpriteInstance {},
	Sprite8: class extends self.ISpriteInstance {},
	Sprite9: class extends self.ISpriteInstance {},
	Sprite10: class extends self.ISpriteInstance {},
	Sprite11: class extends self.ISpriteInstance {},
	Sprite12: class extends self.ISpriteInstance {},
	Texto2: class extends self.ITextInstance {},
	latinhaPx: class extends self.ISpriteInstance {},
	latinha2Px: class extends self.ISpriteInstance {},
	garrafaPx: class extends self.ISpriteInstance {},
	papelPx: class extends self.ISpriteInstance {},
	vidropx: class extends self.ISpriteInstance {}
}